:- סע,
טען_והוסף('list.pro'),
טען_והוסף('patterns.pro'),
טען_והוסף('Amarot.pro'),
טען_והוסף('expert.pro'),
טען_והוסף('display.pro'),
טען_והוסף('newnewmenu3.pro'),
טען_והוסף('menu2.pro'),
טען_והוסף('tomatefet.pro'),
הודעה('טעינת הקבצים הושלמה בהצלחה').